/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

bool is_power_of_two(uint32_t n) {

	bool power_of_two = false;

	if (n == 0){
		return power_of_two;
	}

	/*
	 * To test for power of 2 : (n &(n-1)) == 0
	 */

    return ((n & (n-1)) == 0);

    /*
     * True one liner
     * return (((n & (n-1)) == 0) && (n !=0));
     */
}

int main(void)
{
    /* Loop forever */
	for(;;);
}
