/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdbool.h>
#include <stdint.h>

// Mock function for system time
uint32_t get_system_time_ms(void){

}

// Mock function to read the physical pin
bool read_gpio_pin(void){

}

typedef struct
{
    bool sampled_state;
    bool stable_state;
    uint32_t last_change_time;
} ButtonState;

void button_init(ButtonState *btn){

	bool first_sample = read_gpio_pin();
	bool first_stable = first_sample;
	uint32_t first_timestamp = get_system_time_ms();

	btn->sampled_state = first_sample;
	btn->stable_state = first_stable;
	btn->last_change_time = first_timestamp;

}

bool button_is_pressed(ButtonState *btn) {

	// 1. Read current pin state
	bool current_state = read_gpio_pin();
	uint32_t current_timestamp = get_system_time_ms();

	if (current_state != btn->sampled_state){
		// 3. If it changed, reset your timer.
		btn->last_change_time = current_timestamp;
		btn->sampled_state = current_state;
		// Still de-bouncing
	}

	if (current_timestamp - btn->last_change_time > 50){
		// We made sure the last sampled became stable

		if (btn->stable_state != btn->sampled_state)
		{
		    btn->stable_state = btn->sampled_state;
		}
	}

	if (btn->stable_state == false){
		return true;
	}

    return false;
}

int main (void){

	ButtonState button;

	button_init(&button);

    while (1)
    {
        if (button_is_pressed(&button))
        {
            // Button is stably pressed
        }

        // Other tasks
    }




	return 0;

}
