/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdbool.h>
#include <stdint.h>

// Mock function for system time
uint32_t get_system_time_ms(void);

// Mock function to read the physical pin
bool read_gpio_pin(void);

typedef struct {
    bool last_pin_state;
    uint32_t last_stable_time;
    bool is_debounced;
} ButtonState;

bool is_button_pressed(ButtonState *btn) {

	// 1. Read current pin state
	bool current_state = read_gpio_pin();
	uint32_t current_timestamp = get_system_time_ms();

	// 2. Check if the pin state changed (the button "bounced")
	if (current_state != btn->last_pin_state){
		// 3. If it changed, reset your timer.
		btn->last_stable_time = get_system_time_ms();
		btn->last_pin_state = current_state;
		// Still de-bouncing
		return false;
	}

	// Not else-if just in case the user is holding the button
	if (current_timestamp - btn->last_stable_time > 50){
		if ((current_state == false) && (!btn->is_debounced)){
			btn->is_debounced = true;
			return true;
			// pressed and de-bounced
		}

		// The false would be that the button is already debounce, but the user keeps pressing it
	}

	if (current_state == true) {
	        btn->is_debounced = false;
	}

    return false;
}

int main (void){

	ButtonState button_state = {
			.last_pin_state = true,
			.last_stable_time = 0,
			.is_debounced = false,
	};

	is_button_pressed(&button_state);

}
