/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void array_display(uint32_t const *const p_array, uint32_t size);
void arrays_swap(uint32_t *p_array_1, uint32_t size_1, uint32_t *p_array_2, uint32_t size_2);

int main(void)
{
	/*
    uint8_t array_test[10] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA};
    uint8_t array_size = (sizeof(array_test)/sizeof(array_test[0]));

    array_display(&array_test[2], array_size-2);
    */

	int32_t array_1_size, array_2_size;
	printf("Enter size of Array 1: \n");
	scanf("%ld", &array_1_size);
	printf("Enter size of Array 2: \n");
	scanf("%ld", &array_2_size);

	uint32_t array_1[array_1_size];
	uint32_t array_2[array_2_size];

	printf("Enter the elements of Array 1: \n");

	for (int32_t i=0; i < array_1_size; i++){
		scanf("%ld", &array_1[i]);
	}

	printf("Enter the elements of Array 2: \n");

	for (uint32_t i=0; i < array_2_size; i++){
		scanf("%ld", &array_2[i]);
	}

	array_display(array_1, array_1_size);
	array_display(array_2, array_2_size);

	arrays_swap(array_1, array_1_size, array_2, array_2_size);

}

void array_display(uint32_t const *const p_array, uint32_t size){

    for (int i = 0; i < size; i++){
    	printf("Element at position %d is %ld", i, p_array[i]);
    }
}

void arrays_swap(uint32_t *p_array_1, uint32_t size_1, uint32_t *p_array_2, uint32_t size_2){

	uint32_t len_max = (size_1 < size_2 ? size_1 : size_2);
	uint32_t temp;

	for (uint32_t i = 0; i < len_max; i++){
		temp = p_array_1[i];
		p_array_1[i] = p_array_2[i];
		p_array_2[i] = temp;
	}

}
