/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#define RCC_APB2ENR_ADDR 	0x40021018
#define GPIOx_CRH_ADDR 		0x40011004
#define GPIOx_ODR			0x4001100C

typedef struct {
	uint32_t AFIO_EN	:1;
	uint32_t reserved1	:1;
	uint32_t IOPA_EN	:1;
	uint32_t IOPB_EN	:1;
	uint32_t IOPC_EN	:1;
	uint32_t IOPD_EN	:1;
	uint32_t IOPE_EN	:1;
	uint32_t IOPF_EN	:1;
	uint32_t IOPG_EN	:1;
	uint32_t ADC1_EN	:1;
	uint32_t ADC2_EN	:1;
	uint32_t TIM1_EN	:1;
	uint32_t SPI1_EN	:1;
	uint32_t TIM8_EN	:1;
	uint32_t USART1_EN	:1;
	uint32_t ADC3_EN	:1;
	uint32_t reserved2	:3;
	uint32_t TIM9_EN	:1;
	uint32_t TIM10_EN	:1;
	uint32_t TIM11_EN	:1;
	uint32_t reserved3	:10;
}RCC_APB2ENR_t;

typedef struct {
	uint32_t MODE8		:2;
	uint32_t CONFIG8	:2;
	uint32_t MODE9		:2;
	uint32_t CONFIG9	:2;
	uint32_t MODE10		:2;
	uint32_t CONFIG10	:2;
	uint32_t MODE11		:2;
	uint32_t CONFIG11	:2;
	uint32_t MODE12		:2;
	uint32_t CONFIG12	:2;
	uint32_t MODE13		:2;
	uint32_t CONFIG13	:2;
	uint32_t MODE14		:2;
	uint32_t CONFIG14	:2;
	uint32_t MODE15		:2;
	uint32_t CONFIG15	:2;
}GPIOx_CRH_t;

typedef struct {
	uint32_t PIN0		:1;
	uint32_t PIN1		:1;
	uint32_t PIN2		:1;
	uint32_t PIN3		:1;
	uint32_t PIN4		:1;
	uint32_t PIN5		:1;
	uint32_t PIN6		:1;
	uint32_t PIN7		:1;
	uint32_t PIN8		:1;
	uint32_t PIN9		:1;
	uint32_t PIN10		:1;
	uint32_t PIN11		:1;
	uint32_t PIN12		:1;
	uint32_t PIN13		:1;
	uint32_t PIN14		:1;
	uint32_t PIN15		:1;
	uint32_t reserved	:16;
}GPIOx_ODR_t;



int main(void)
{

	volatile RCC_APB2ENR_t *const pRCCAPBEEnAddr = (RCC_APB2ENR_t*)RCC_APB2ENR_ADDR;
	volatile GPIOx_CRH_t *const pGPIOCCRAddr = (GPIOx_CRH_t*)GPIOx_CRH_ADDR;
	volatile GPIOx_ODR_t *const pGPIOCOutAddr = (GPIOx_ODR_t*)GPIOx_ODR;

	// Enable GPIOC
	pRCCAPBEEnAddr->IOPC_EN = 1;

	// Configure Pin 13
	pGPIOCCRAddr->MODE13 = 1;
	pGPIOCCRAddr->CONFIG13 = 0;

    /* Loop forever */
	while(1){
		pGPIOCOutAddr->PIN13 ^= 1;

		for (uint32_t i = 0; i < 300000; i++);

		//pGPIOCOutAddr->PIN13 = 0;

		//for (uint32_t i = 0; i < 300000; i++);
	}
}
