/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

typedef struct{
	uint8_t 	crc;
	uint8_t 	status;
	uint16_t 	payload;
	uint8_t 	batt;
	uint8_t 	sensor;
	uint8_t		longAddr;
	uint8_t		shortAddr;
	uint8_t		addrMode;
}SensorData_t;

// Using bitfields
typedef struct{
	uint32_t 	crc			:2;
	uint32_t 	status		:1;
	uint32_t 	payload 	:12;
	uint32_t 	batt		:3;
	uint32_t 	sensor		:3;
	uint32_t	longAddr	:8;
	uint32_t	shortAddr	:2;
	uint32_t	addrMode	:1;
}SensorData2_t;


// Using unions
union SensorData {
	uint32_t value;
	struct {
		uint32_t 	crc			:2;
		uint32_t 	status		:1;
		uint32_t 	payload 	:12;
		uint32_t 	batt		:3;
		uint32_t 	sensor		:3;
		uint32_t	longAddr	:8;
		uint32_t	shortAddr	:2;
		uint32_t	addrMode	:1;
	}value_fields;
};

int main(void)
{

	uint32_t userData = 0x1234EEEE;
	//prinft("Enter number: \n");
	//scanf("%lx", &userData);

	SensorData_t sensorData;
	SensorData_t *p_sensorData = &sensorData;

	/*Field extractions*/

	// Bit 0-1: CRC
	p_sensorData->crc =(uint8_t)(userData & 0x3);

	// Bit 2: Status
	p_sensorData->status = (uint8_t)((userData >> 2) & 0x1);

	// Bits 3 - 14: Payload
	p_sensorData->payload = (uint16_t)((userData >> 3) & 0xFFF);

	// Bits 15 - 17: Battery
	p_sensorData->batt = (uint8_t)((userData >> 15) & 0x7);

	// Bits 18 - 20: Sensor
	p_sensorData->sensor = (uint8_t)((userData >> 18) & 0x7);

	// Bits 21 - 28: Long Address
	p_sensorData->longAddr = (uint8_t)((userData >> 21) & 0xFF);

	// Bits 29 - 30: Short Address
	p_sensorData->shortAddr = (uint8_t)((userData >> 29) & 0x3);

	// Bit 31: Mode
	p_sensorData->addrMode= (uint8_t)((userData >> 31) & 0x1);

	printf("Members of the structure: \n");
	printf("CRC: %X \n", p_sensorData->crc);
	printf("Status: %X \n", p_sensorData->status);
	printf("Payload: %X \n", p_sensorData->payload);
	printf("Battery: %X \n", p_sensorData->batt);
	printf("Sensor: %X \n", p_sensorData->sensor);
	printf("Long Address: %X \n", p_sensorData->longAddr);
	printf("Short Address: %X \n", p_sensorData->shortAddr);
	printf("Address mode: %X \n", p_sensorData->addrMode);

	//for(;;);
}
